const customers = [
    {
      firstName: "John",
      lastName: "Abramson",
      businessName: "Testing",
      customerType: "Individual",
      email: "testing1@gmail.com",
      primaryPhone: 1,
      primaryAddress: 1,
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Emily",
      lastName: "Adams",
      businessName: "Testing 2",
      customerType: "Individual",
      email: "testing2@gmail.com",
      primaryPhone: 2,
      primaryAddress: 2,
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Julie",
      lastName: "Ash",
      businessName: "Testing 3",
      customerType: "Individual",
      email: "testing3@gmail.com",
      primaryPhone: 3,
      primaryAddress: 3,
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Avila",
      lastName: "Fernando",
      businessName: "Testing 4",
      customerType: "Individual",
      email: "testing4@gmail.com",
      primaryPhone: 4,
      primaryAddress: 4,
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
  ];

module.exports = customers