const customers = [
    {
      firstName: "Matias",
      lastName: "Fuenzalida",
      businessName: "Testing",
      customerType: "Individual",
      email: "testing1@gmail.com",
      phone: "555-555-555",
      address: "404 test street",
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Jose",
      lastName: "Carreno",
      businessName: "Testing 2",
      customerType: "Individual",
      email: "testing2@gmail.com",
      phone: "655-555-555",
      address: "405 test street",
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Enmanuel",
      lastName: "Carbonell",
      businessName: "Testing 3",
      customerType: "Individual",
      email: "testing3@gmail.com",
      phone: "755-555-555",
      address: "405 test street",
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
    {
      firstName: "Abel",
      lastName: "Castillo",
      businessName: "Testing 4",
      customerType: "Individual",
      email: "testing4@gmail.com",
      phone: "855-555-555",
      address: "405 test street",
      city: "test city",
      state: "Florida",
      zip: "33015",
    },
  ];

module.exports = customers